# Orbit CI Template
# Copy to .github/workflows/ci.yml

name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    # Uncomment for matrix testing
    # strategy:
    #   matrix:
    #     node-version: [18, 20, 22]  # Node.js
    #     python-version: ['3.10', '3.11', '3.12']  # Python

    steps:
      - uses: actions/checkout@v4

      # === Node.js ===
      # Uncomment for Node.js projects
      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 20
      #     cache: 'npm'
      #
      # - name: Install dependencies
      #   run: npm ci
      #
      # - name: Run tests
      #   run: npm test
      #
      # - name: Build
      #   run: npm run build --if-present

      # === Python ===
      # Uncomment for Python projects
      # - name: Setup Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.11'
      #     cache: 'pip'
      #
      # - name: Install dependencies
      #   run: |
      #     pip install -r requirements.txt
      #     pip install pytest
      #
      # - name: Run tests
      #   run: pytest

      # === Go ===
      # Uncomment for Go projects
      # - name: Setup Go
      #   uses: actions/setup-go@v5
      #   with:
      #     go-version: '1.21'
      #
      # - name: Build
      #   run: go build -v ./...
      #
      # - name: Run tests
      #   run: go test -v ./...

      # === Rust ===
      # Uncomment for Rust projects
      # - name: Setup Rust
      #   uses: dtolnay/rust-toolchain@stable
      #
      # - name: Build
      #   run: cargo build --release
      #
      # - name: Run tests
      #   run: cargo test --release

      - name: Placeholder
        run: echo "Configure CI for your project type above"
